# Generated by Django 4.0.6 on 2022-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('serie', models.CharField(choices=[('Y1', 'Primeiro ano'), ('Y2', 'Segundo ano'), ('Y3', 'Terceiro ano')], default='Y1', max_length=2)),
            ],
        ),
    ]
