# Generated by Django 4.0.6 on 2022-07-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.aluno')),
            ],
        ),
    ]
